name: Extract TGZ or ZIP into Repo

on:
  workflow_dispatch:  # Allows manual triggering from GitHub Actions

jobs:
  extract-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Extraction Tools
        run: sudo apt-get install -y tar unzip

      - name: Check File Type
        run: file file.tgz

      - name: Extract the File (Auto Detect Format)
        run: |
          if file file.tgz | grep -q "gzip compressed"; then
            echo "Extracting Gzip Compressed Tar File (.tgz or .tar.gz)"
            mkdir extracted_files
            tar -xvzf file.tgz -C extracted_files
          elif file file.tgz | grep -q "POSIX tar archive"; then
            echo "Extracting Uncompressed Tar File (.tar)"
            mkdir extracted_files
            tar -xvf file.tgz -C extracted_files
          elif file file.tgz | grep -q "Zip archive data"; then
            echo "Extracting ZIP File (.zip)"
            mkdir extracted_files
            unzip file.tgz -d extracted_files
          else
            echo "Unknown file format. Extraction failed!"
            exit 1
          fi

      - name: Commit and Push Extracted Files
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git

          git checkout -b extracted-files  # Create a new branch for extracted files
          git add extracted_files/*  # Add all extracted files
          git commit -m "Extracted archive contents"
          git push origin extracted-files  # Push extracted files to a new branch
